AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  LambdaTest:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-test/
      Handler: index.handler
      Runtime: nodejs12.x
      Policies:
        S3ReadPolicy:
          BucketName: mypfetestbucket
  s3python:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3-python/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        S3ReadPolicy:
          BucketName: mypfetestbucket
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mypfetestbucket
      NotificationConfiguration:
        QueueConfigurations:
          -
            Event: 's3:ObjectCreated:*'
            Queue: !GetAtt SimpleQueue.Arn
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName : SimpleQueue
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  LambdaTest:
    Description: "Hello World Lambda test ARN"
    Value: !GetAtt LambdaTest.Arn    
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
