service: lambda-test-sam

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - .vscode/**
    - package.json
    - package-lock.json
    - README.md
    - .editorconfig
    - coverage/**
    - events/**
    - ./**.test.js

functions:
  tempo:
    handler: index.handler
    events:
      - http:
          path: event
          method: post
